name: pomodorotimer
description: Aplicação de timer pomodoro desenvolvida em Flutter para a avaliação N1 da matéria de Desenvolvimento de Dispositivos Móveis

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:

  flutter:
    sdk: flutter

  provider: ^6.0.3
  page_transition: ^2.0.9
  animated_splash_screen: ^1.3.0
  carbon_icons: ^0.0.1
  google_fonts: ^3.0.1
  google_nav_bar: ^5.0.6
  curved_navigation_bar: ^1.0.3

dev_dependencies:
flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true